SCREEN_WIDTH = 1400
SCREEN_HEIGHT = 800

PLANT_COUNT = 500
PREY_COUNT = 60
PREDATOR_COUNT = 16

EAT_RADIUS = 5
PLANT_ENERGY = 50
PREY_ENERGY_START = 400
PREDATOR_ENERGY_START = 400

PREY_REPRODUCTION_AGE = 300
PREY_REPRODUCTION_TIME = 500
PREDATOR_REPRODUCTION_AGE = 800
PREDATOR_REPRODUCTION_TIME = 800

FLEE_TIMER = 60  # number of ticks to flee

MOVEMENT_COST = 1
SPRINT_COST = 2

FPS = 30

SHOW_VISION_CONES = True